#!/usr/bin/env python3
"""Declarative preview wiring. Only the nonproduction controller creates DB secrets."""
from pathlib import Path
import yaml

ROOT=Path(__file__).resolve().parents[1]
APPS={
 'hkh': [('backend','backend','HKH')],
 'hkh-autopilot': [('backend','backend','HKH')],
 'product-factory': [('runtime','runtime','PF'),('product-factory-backend','backend','PF')],
 'personal-news-feed': [('backend','backend','PNF')],
}
def wiring(name,container,prefix):
 user=prefix+'_DB_USERNAME' if prefix=='PF' else prefix+'_DATABASE_USER'
 password=prefix+'_DB_PASSWORD' if prefix=='PF' else prefix+'_DATABASE_PASSWORD'
 url=prefix+'_DB_URL' if prefix=='PF' else prefix+'_DATABASE_URL'
 env=[{'name':key,'value':None,'valueFrom':{'secretKeyRef':{'name':'preview-postgres','key':field}}} for key,field in [(url,'url'),(user,'username'),(password,'password'),('SPRING_DATASOURCE_URL','url'),('SPRING_DATASOURCE_USERNAME','username'),('SPRING_DATASOURCE_PASSWORD','password')]]
 env += [{'name':'SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE','value':'5'},{'name':'SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE','value':'0'}]
 if prefix=='PNF':
  env += [{'name':key,'value':value,'valueFrom':None} for key,value in [('PNF_AGENT_RUNTIME_TOKEN',''),('PNF_GOOGLE_CLIENT_ID',''),('PNF_GOOGLE_USERS','preview@pnf.invalid'),('APP_JWT_SECRET','')]]
 return {'apiVersion':'apps/v1','kind':'Deployment','metadata':{'name':name},'spec':{'template':{'metadata':{'labels':{'postgres.vdzonsoftware.nl/client':'true'}},'spec':{'containers':[{'name':container,'env':env,'volumeMounts':[{'name':'central-postgres-ca','mountPath':'/etc/postgres-ca','readOnly':True}]}],'volumes':[{'name':'central-postgres-ca','secret':{'secretName':'preview-postgres','items':[{'key':'ca.crt','path':'ca.crt'}]}}]}}}}

for app,backends in APPS.items():
 path=ROOT/'manifests/root-app/apps'/(app+'-applicationset.yaml')
 config=yaml.safe_load(path.read_text());ks=config['spec']['template']['spec']['source']['kustomize']
 # Idempotent reruns replace only patches generated by this script.
 patches=[p for p in ks.get('patches',[]) if 'preview-postgres' not in p['patch'] and '$patch: delete' not in p['patch']]
 for name,container,prefix in backends:
  patches.append({'target':{'kind':'Deployment','name':name},'patch':yaml.safe_dump(wiring(name,container,prefix),sort_keys=False)})
 for kind,name in [('StatefulSet','database'),('Deployment','postgres'),('Service','database'),('Service','postgres'),('PersistentVolumeClaim','database-data'),('PersistentVolumeClaim','postgres-data')]:
  patches.append({'target':{'kind':kind,'name':name},'patch':yaml.safe_dump({'$patch':'delete','apiVersion':'apps/v1' if kind in ['StatefulSet','Deployment'] else 'v1','kind':kind,'metadata':{'name':name}},sort_keys=False)})
 if app=='product-factory':
  patch={'apiVersion':'apps/v1','kind':'Deployment','metadata':{'name':'product-factory-backend'},'spec':{'template':{'spec':{'containers':[{'name':'backend','env':[{'name':'PF_PUBLIC_FRONTEND_URL','value':'https://product-factory-pr-{{.number}}.vdzonsoftware.nl'},{'name':'PF_PUBLIC_BACKEND_URL','value':'https://product-factory-api-pr-{{.number}}.vdzonsoftware.nl'}]}]}}}}
  patches.append({'target':{'kind':'Deployment','name':'product-factory-backend'},'patch':yaml.safe_dump(patch,sort_keys=False)})
  for component in ['backend','frontend']:
   image='ghcr.io/robbertvdzon/product-factory-'+component
   value=image+'='+image+':sha-{{.head_sha}}'
   if value not in ks['images']:ks['images'].append(value)
 ks['patches']=patches
 path.write_text(yaml.safe_dump(config,sort_keys=False,width=140))

# Current HKH branches also render correctly without ApplicationSet overrides.
for app in ['hkh','hkh-autopilot']:
 folder=ROOT.parent/app/'deploy/overlays/preview'
 path=folder/'kustomization.yaml';config=yaml.safe_load(path.read_text())
 config['patches']=[p for p in config['patches'] if p.get('target',{}).get('name')!='database-data' and p.get('path')!='central-postgres-patch.yaml']
 for kind,name in [('StatefulSet','database'),('Service','database'),('PersistentVolumeClaim','database-data')]:
  config['patches'].append({'target':{'kind':kind,'name':name},'patch':yaml.safe_dump({'$patch':'delete','apiVersion':'apps/v1' if kind=='StatefulSet' else 'v1','kind':kind,'metadata':{'name':name}},sort_keys=False)})
 config['patches'].append({'path':'central-postgres-patch.yaml'})
 path.write_text(yaml.safe_dump(config,sort_keys=False))
 (folder/'central-postgres-patch.yaml').write_text(yaml.safe_dump(wiring('backend','backend','HKH'),sort_keys=False))
print('Preview ApplicationSets and current HKH overlays wired to isolated nonproduction databases.')
