---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-timemachine-credentials
  namespace: smb-timemachine
spec:
  encryptedData:
    SAMBA_PASSWORD: AgCOHvUXAZ/cJRWu5midsfbsmuRIYsfOG8CKk+KPyq2GkOR6odzIHL8HWLiqcYUJsjYFmyavGvpe/U+CCLIjM7GYTLSu44sOwyfVfRGGcFfgF7GcCzuMMM37dbLWSuR2Sb0bdQfk6TCSEq2NrozafMoM6SRvYKmtiuYN/SKedJWE+YuG0wqcUSNBuxv1Q1Fso2KaqUMWnKq5lA9eO5yBk+ccl4VAZgriLsRzFA+cBJOhBMrxFsxVYnacUaD8/qRIIieEi4TwrErRmbikziKGPLix0bwo3I9of6Gu/jABnx5fN5CMtWJlqd2t4D44aJGqQsGXZ4BFSl/W2mekgXYDXo7Z3LaiHU/pklR8/xmvtaDZ5p8+mTz7XnfWeTDRDd/sJc97gJVm9qzeCoz1WqT+5+Dhd9DTuCA9yMt7DPqzHIumbKLmA5N2raH79CRmHY1NMJaBCeeN1jS6313ER5cSBUkOqKm59x5CRwoI1TvHdCScMEFAyKYbp67k9JvP8CnhljEaQ09Bbssp5G4oNQtcnJMkrukdj5cy8/lSnMXZjv3php5LBOZhmw4VCO0F0vxU7LY94UjEeIuCYgA7PUPO92VT+W/tFp5tJFm+/H/FWMzeluCOxSV6V7H4mVZITzts/DC3PtA9C224r/YXGDOnB/Q5CGfEi9QFjaEWEdRDU/jWBleNDj87ymMgreOs39m5Z0dg2lFYxdFw5VHlFcsdCbOOUhaAww==
  template:
    metadata:
      name: samba-timemachine-credentials
      namespace: smb-timemachine
