apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole-extra-view.yaml
  - clusterrole-preview-cleanup.yaml
  - clusterrolebindings.yaml
  - token-secret.yaml
