apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
- sealed-credentials.yaml
- sealed-tls.yaml
- monitoring.yaml
- operations.yaml
- sealed-backup-encryption.yaml
